apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: 2017ht01561
    provider: https://github.com
    providerKind: github
    repositories:
    - name: liberty
    - name: node
    - name: node-http
    - name: node-http-watch-pipeline-activity
    - name: nodechat1
    - name: quickstart
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
